#data source properties
spring:
  datasource:
    data-source-class-name: org.h2.jdbcx.JdbcDataSource
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql

# JPA properties
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 9006
